### ISSUE TITLE
`/oauth/authorize` does not redirect

### ISSUE THREAD

**Issue by ryansteil-pl** [clerk/javascript#4732]
### Preliminary Checks

- [X] I have reviewed the documentation: https://clerk.com/docs

- [X] I have searched for existing issues: https://github.com/clerk/javascript/issues

- [X] I have not already reached out to Clerk support via email or Discord (if you have, no need to open an issue here)

- [X] This issue is not a question, general help request, or anything other than a bug report directly related to Clerk. Please ask questions in our Discord community: https://clerk.com/discord.

### Reproduction

n/a

### Publishable key

n/a

### Description

I successfully have Clerk setup as an [OAuth 2 Provider](https://clerk.com/docs/advanced-usage/clerk-idp).

However, I noticed that calling [`/oauth/authorize`](https://clerk.com/docs/reference/frontend-api/tag/OAuth2-Identify-Provider#operation/requestOAuthAuthorize) **does not** successfully redirect after login using the Sign-in page on application domain. It **does** successfully redirect if using the Sign-in page on Account Portal.

![Screenshot 2024-12-07 at 10 55 50 PM](https://github.com/user-attachments/assets/356c81a2-e8a2-4724-b802-01706084ed65)

### Environment

```Shell
n/a
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Clerk!

[reproduction]: https://clerkdev.notion.site/clerkdev/Creating-a-Minimal-Reproduction-0436afc4203f41aa9aa8700968aaef48

**Comment by clerk-cookie** [comment]
Hello 👋

In an effort to keep our GitHub issues clean and focused, we close any issues that are awaiting a reproduction after 8 days on inactivity, and it has been 7 days. This issue will be closed tomorrow unless a reproduction is provided. If it takes longer than this to get a reproduction, that's ok, just drop a comment and we will remove the Stale label.

[How to create a minimal reproduction](https://clerkdev.notion.site/clerkdev/Creating-a-Minimal-Reproduction-0436afc4203f41aa9aa8700968aaef48)

Thanks for being a part of the Clerk community! 🙏

**Comment by clerk-cookie** [comment]
After 8 days without a reproduction being supplied, we are closing this issue. Keep in mind, I'm just a robot, so if I've closed this issue in error, please reply here and my human colleagues will reopen it. Likewise if a reproduction is prepared after it has been closed.
